build_image:
    image: docker:git
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/skatebrus/nodejs-warriars/login .
        - docker push registry.gitlab.com/skatebrus/nodejs-warriars/login:latest
    only:
        - master
